name: localstack-action-example
on: push
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Start LocalStack
        env:
          GOPATH: /home/runner/work/kpt-functions-catalog/functions/go
          GO111MODULE: on
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
        run: |
          # install LocalStack cli and awslocal
          pip install localstack awscli-local[ver1]
          # Make sure to pull the latest version of the image
          docker pull localstack/localstack
          # Start LocalStack in the background
          localstack start -d
          # Wait 30 seconds for the LocalStack container to become ready before timing out
          echo "Waiting for LocalStack startup..."
          localstack wait -t 30
          echo "Startup complete"          
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Run some Tests against LocalStack
        run: |
          terraform init
          terraform apply --auto-approve
          echo "Test Execution complete!"
